# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'notasecretproject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

 	pod 'Firebase/Core', '~> 5.20.1'
	pod 'Firebase/Firestore', '~> 5.20.1'
  target 'notasecretprojectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'notasecretproject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for notasecretproject-tvOS

  target 'notasecretproject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
